package Models.Internship;

public enum Country {
        ALBANIA,
        AUSTRIA,
        BELGIUM,
        BOSNIA_AND_HERZEGOVINA,
        BULGARIA,
        CROATIA,
        CYPRUS,
        CZECH_REPUBLIC,
        DENMARK,
        ESTONIA,
        FINLAND,
        FRANCE,
        GERMANY,
        GREECE,
        HUNGARY,
        ICELAND,
        IRELAND,
        ITALY,
        KOSOVO,
        LATVIA,
        LIECHTENSTEIN,
        LITHUANIA,
        LUXEMBOURG,
        MALTA,
        MOLDOVA,
        MONTENEGRO,
        NETHERLANDS,
        NORTH_MACEDONIA,
        NORWAY,
        POLAND,
        PORTUGAL,
        ROMANIA,
        SERBIA,
        SLOVAKIA,
        SLOVENIA,
        SWEDEN,
        TURKEY,
        UKRAINE,
        UNITED_KINGDOM
    }

